# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 26 Jun 2014 04:18:52 +0000
*	@ALL	0
*	@user	8
*	@visitor	1
캐릭터	@ALL	0
캐릭터	@user	1
캐릭터	@visitor	2
