<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: velmont
 * Date: Mon, 04 Sep 2017 15:19:25 +0900
 */

$conf['title'] = '프로젝트 위키';
$conf['lang'] = 'ko';
$conf['license'] = 'cc-by-sa';
$conf['tocminheads'] = '1';
$conf['maxtoclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['updatecheck'] = 0;
$conf['plugin']['odt']['outline_list_style'] = 'Numbers';
$conf['plugin']['odt2dw']['parserMimeTypeAuthorized'] = 'application/vnd.oasis.opendocument.text
application/octetstream';

// end auto-generated content
